"""Public facade for the Agents domain.

Re-exports the public surface of the ``core.agents`` submodules
(``definition`` / ``runner`` / ``contract`` / ``prompt`` / ``versioning``)
so external callers import from this one place instead of reaching into
submodules. The ``agents-facade`` import-linter contract enforces that.
"""

from agentbox.core.agents.definition import (
    ExecutionConfig as ExecutionConfig,
    PythonAgentConfig as PythonAgentConfig,
    RuntimeConfig as RuntimeConfig,
    build_config_json_payload as build_config_json_payload,
)
from agentbox.core.agents.runner import (
    engine_load_failure as engine_load_failure,
    list_engines as list_engines,
    resolve_engine as resolve_engine,
    resolve_engine_by_name as resolve_engine_by_name,
)
from agentbox.core.agents.versioning import (
    AgentDriftStatus as AgentDriftStatus,
    PromptDoc as PromptDoc,
    PromptError as PromptError,
    build_agent_snapshot as build_agent_snapshot,
    build_config_json_str as build_config_json_str,
    check_drift as check_drift,
    startup_sweep as startup_sweep,
)
from agentbox.core.agents.validation import (
    OutputConfig as OutputConfig,
    check_output as check_output,
    resolve_output_config as resolve_output_config,
    resolve_schema as resolve_schema,
)
from agentbox.core.agents.composition import (
    BindingsBundleSource as BindingsBundleSource,
    Bundle as Bundle,
    BundleSource as BundleSource,
    ComposedReference as ComposedReference,
    ComposeResult as ComposeResult,
    CompositionPreview as CompositionPreview,
    OutputSchemaInfo as OutputSchemaInfo,
    PreviewError as PreviewError,
    ReferencePreview as ReferencePreview,
    ReferenceSpec as ReferenceSpec,
    build_prompt as build_prompt,
    build_runtime_view as build_runtime_view,
    compose as compose,
    compose_from_source as compose_from_source,
    load_bundle_from_bindings as load_bundle_from_bindings,
    preview as preview,
    precompose_check as precompose_check,
    render_agent_prompt_preview as render_agent_prompt_preview,
    render_document as render_document,
    render_folder_manifest as render_folder_manifest,
    render_for_type as render_for_type,
    render_schema as render_schema,
    render_script as render_script,
    render_skill_primer as render_skill_primer,
    resolve_agent_prompt_bindings as resolve_agent_prompt_bindings,
    resolve_prompt as resolve_prompt,
    validate_input as validate_input,
)
from agentbox.core.data.composition import (
    AgentRuntimeView as AgentRuntimeView,
    ComposedPrompt as ComposedPrompt,
    HttpValidatorConfig as HttpValidatorConfig,
    ScriptValidatorConfig as ScriptValidatorConfig,
    ValidationEngine as ValidationEngine,
    ValidationResult as ValidationResult,
)

__all__ = [
    "AgentDriftStatus",
    "AgentRuntimeView",
    "BindingsBundleSource",
    "Bundle",
    "BundleSource",
    "ComposedPrompt",
    "ComposedReference",
    "ComposeResult",
    "CompositionPreview",
    "ExecutionConfig",
    "HttpValidatorConfig",
    "OutputConfig",
    "OutputSchemaInfo",
    "PreviewError",
    "PromptDoc",
    "PromptError",
    "PythonAgentConfig",
    "ReferencePreview",
    "ReferenceSpec",
    "RuntimeConfig",
    "ScriptValidatorConfig",
    "ValidationEngine",
    "ValidationResult",
    "build_agent_snapshot",
    "build_config_json_payload",
    "build_config_json_str",
    "build_prompt",
    "build_runtime_view",
    "check_drift",
    "check_output",
    "compose",
    "compose_from_source",
    "engine_load_failure",
    "list_engines",
    "load_bundle_from_bindings",
    "preview",
    "precompose_check",
    "resolve_engine",
    "resolve_engine_by_name",
    "render_agent_prompt_preview",
    "render_document",
    "render_folder_manifest",
    "render_for_type",
    "render_schema",
    "render_script",
    "render_skill_primer",
    "resolve_agent_prompt_bindings",
    "resolve_output_config",
    "resolve_prompt",
    "resolve_schema",
    "startup_sweep",
    "validate_input",
]
