"""initial schema

Revision ID: 8aa39c682b93
Revises: 
Create Date: 2026-05-21 19:52:38.496408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aa39c682b93'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_sync',
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('proxy_path', sa.String(), nullable=True),
    sa.Column('sync_mode', sa.String(), server_default='manual', nullable=False),
    sa.Column('sync_policy', sa.String(), server_default='db_wins', nullable=False),
    sa.Column('last_file_hash', sa.String(), nullable=True),
    sa.Column('last_file_mtime', sa.String(), nullable=True),
    sa.Column('last_sync_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_table('agent_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source_path', sa.String(), nullable=False),
    sa.Column('source_format', sa.String(), nullable=False),
    sa.Column('content_snapshot', sa.String(), nullable=False),
    sa.Column('prompt_snapshot', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('changelog', sa.String(), server_default='', nullable=False),
    sa.Column('is_legacy', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_versions_agent', 'agent_versions', ['agent_id', 'version'], unique=True)
    op.create_table('prompt_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('author', sa.String(), server_default='system', nullable=False),
    sa.Column('changelog', sa.String(), server_default='', nullable=False),
    sa.Column('is_draft', sa.Integer(), server_default='0', nullable=False),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_prompt_versions_agent', 'prompt_versions', ['agent_id', 'version'], unique=True)
    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('workdir', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('last_used_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_version_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['agent_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_version_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('relative_path', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('sha256', sa.String(), nullable=False),
    sa.Column('source_uri', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['agent_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'relative_path', name='uq_version_file_path')
    )
    op.create_index('idx_agent_version_files_version', 'agent_version_files', ['version_id'], unique=False)
    op.create_table('agent_version_ratings',
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('rater', sa.String(), nullable=False),
    sa.Column('rated_at', sa.String(), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='rating_range'),
    sa.ForeignKeyConstraint(['version_id'], ['agent_versions.id'], ),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_table('runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('input', sa.String(), nullable=False),
    sa.Column('output', sa.String(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('workdir', sa.String(), nullable=True),
    sa.Column('transcript_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('finished_at', sa.String(), nullable=True),
    sa.Column('config_digest', sa.String(), nullable=True),
    sa.Column('agent_version_id', sa.Integer(), nullable=True),
    sa.Column('composition_snapshot', sa.String(), nullable=True),
    sa.Column('rendered_prompt', sa.String(), nullable=True),
    sa.Column('variables', sa.String(), nullable=True),
    sa.Column('validation_status', sa.String(), nullable=True),
    sa.Column('validation_errors', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['agent_version_id'], ['agent_versions.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('runs_by_agent', 'runs', ['agent_id', 'created_at'], unique=False)
    op.create_index('runs_by_status', 'runs', ['status', 'created_at'], unique=False)
    op.create_table('guardrail_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ok', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('attempt', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.CheckConstraint('ok IN (0, 1)', name='guardrail_ok_bool'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run_prompts',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('fragments', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('usage',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), server_default='0', nullable=True),
    sa.Column('output_tokens', sa.Integer(), server_default='0', nullable=True),
    sa.Column('cache_read_tokens', sa.Integer(), server_default='0', nullable=True),
    sa.Column('cache_write_tokens', sa.Integer(), server_default='0', nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usage')
    op.drop_table('run_prompts')
    op.drop_table('guardrail_results')
    op.drop_index('runs_by_status', table_name='runs')
    op.drop_index('runs_by_agent', table_name='runs')
    op.drop_table('runs')
    op.drop_table('agent_version_ratings')
    op.drop_index('idx_agent_version_files_version', table_name='agent_version_files')
    op.drop_table('agent_version_files')
    op.drop_table('agent_version_comments')
    op.drop_table('sessions')
    op.drop_index('idx_prompt_versions_agent', table_name='prompt_versions')
    op.drop_table('prompt_versions')
    op.drop_index('idx_agent_versions_agent', table_name='agent_versions')
    op.drop_table('agent_versions')
    op.drop_table('agent_sync')
    # ### end Alembic commands ###
