#!/usr/bin/env python3
"""Fetch available models from Claude Code and OpenCode CLIs and update the
model registry at src/agentbox/core/config_generation/schemas/_model_registry.py.

Run after upgrading Claude Code or OpenCode:

    uv run python scripts/fetch_models.py

Requirements:
  - claude CLI in PATH (or CLAUDE_BIN env var)
  - opencode CLI in PATH (or OPENCODE_BIN env var)
  - ANTHROPIC_API_KEY set (for Claude model list)

The script writes the registry file and prints a diff summary. Commit the
result alongside the version bump in schemas/versions.py.
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
REGISTRY_PATH = (
    REPO_ROOT
    / "src"
    / "agentbox"
    / "core"
    / "config_generation"
    / "schemas"
    / "_model_registry.py"
)
VERSIONS_PATH = (
    REPO_ROOT
    / "src"
    / "agentbox"
    / "core"
    / "config_generation"
    / "schemas"
    / "versions.py"
)

CLAUDE_BIN = os.environ.get("CLAUDE_BIN", "claude")
OPENCODE_BIN = os.environ.get("OPENCODE_BIN", "opencode")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _run(cmd: list[str]) -> str:
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
    if result.returncode != 0:
        raise RuntimeError(
            f"{cmd[0]} failed (exit {result.returncode}):\n{result.stderr.strip()}"
        )
    return result.stdout.strip()


def _get_version(bin_path: str) -> str:
    try:
        out = _run([bin_path, "--version"])
        # Claude: "2.1.111 (Claude Code)"  OpenCode: "1.14.48"
        return out.split()[0]
    except Exception as exc:
        print(f"  Warning: could not get {bin_path} version: {exc}", file=sys.stderr)
        return "unknown"


def _fetch_claude_models() -> frozenset[str]:
    """Fetch Claude model IDs via the Anthropic API."""
    try:
        import anthropic  # type: ignore[import]

        client = anthropic.Anthropic()
        models = [m.id for m in client.models.list().data]
        # Add short aliases the claude_code runner accepts
        aliases = {"opus", "sonnet", "haiku"}
        return frozenset(models) | aliases
    except ImportError:
        print(
            "  anthropic package not installed — falling back to claude CLI",
            file=sys.stderr,
        )
    except Exception as exc:
        print(f"  Anthropic API error: {exc}", file=sys.stderr)

    # Fallback: parse `claude models` output
    try:
        raw = _run([CLAUDE_BIN, "models"])
        models = re.findall(r"claude-[\w.-]+", raw)
        return frozenset(models) | {"opus", "sonnet", "haiku"}
    except Exception as exc:
        print(f"  claude models fallback failed: {exc}", file=sys.stderr)
        return frozenset()


def _fetch_opencode_models() -> frozenset[str]:
    """Fetch OpenCode model IDs via 'opencode models --json' (if available)."""
    try:
        raw = _run([OPENCODE_BIN, "models", "--json"])
        data = json.loads(raw)
        if isinstance(data, list):
            return frozenset(str(m.get("id", m)) for m in data if m)
        if isinstance(data, dict):
            return frozenset(data.keys())
    except Exception:
        pass

    # Fallback: parse text output
    try:
        raw = _run([OPENCODE_BIN, "models"])
        # Lines like "anthropic/claude-sonnet-4-6   Claude Sonnet 4.6"
        models: list[str] = []
        for line in raw.splitlines():
            parts = line.split()
            if parts and "/" in parts[0]:
                models.append(parts[0])
        return frozenset(models) | {"opus", "sonnet", "haiku"}
    except Exception as exc:
        print(f"  opencode models failed: {exc}", file=sys.stderr)
        return frozenset()


def _read_versions() -> tuple[str, str]:
    """Read pinned versions from versions.py."""
    text = VERSIONS_PATH.read_text()
    cc = re.search(r'CLAUDE_CODE_VERSION\s*=\s*"([^"]+)"', text)
    oc = re.search(r'OPENCODE_VERSION\s*=\s*"([^"]+)"', text)
    return (cc.group(1) if cc else "?"), (oc.group(1) if oc else "?")


def _write_registry(
    claude_models: frozenset[str],
    opencode_models: frozenset[str],
    claude_version: str,
    opencode_version: str,
) -> None:
    def _fmt(models: frozenset[str]) -> str:
        return "\n".join(f'    "{m}",' for m in sorted(models))

    content = f'''\
# Auto-generated by scripts/fetch_models.py
# Claude Code {claude_version} / OpenCode {opencode_version}
# Regenerate: uv run python scripts/fetch_models.py

from __future__ import annotations

# ---------------------------------------------------------------------------
# Claude Code (Anthropic) — full model IDs accepted by the API + short aliases
# used by the claude runner (e.g. "sonnet" → claude-sonnet-4-6).
# ---------------------------------------------------------------------------
CLAUDE_MODELS: frozenset[str] = frozenset({{
{_fmt(claude_models)}
}})

# ---------------------------------------------------------------------------
# OpenCode — provider/model strings accepted by OpenCode\'s model picker.
# Format: "<provider>/<model-id>" or bare model IDs for default provider.
# ---------------------------------------------------------------------------
OPENCODE_MODELS: frozenset[str] = frozenset({{
{_fmt(opencode_models)}
}})
'''
    REGISTRY_PATH.write_text(content)


def _update_versions_file(claude_version: str, opencode_version: str) -> None:
    text = VERSIONS_PATH.read_text()
    text = re.sub(
        r'CLAUDE_CODE_VERSION\s*=\s*"[^"]+"',
        f'CLAUDE_CODE_VERSION = "{claude_version}"',
        text,
    )
    text = re.sub(
        r'OPENCODE_VERSION\s*=\s*"[^"]+"',
        f'OPENCODE_VERSION = "{opencode_version}"',
        text,
    )
    VERSIONS_PATH.write_text(text)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    print("Fetching Claude Code version...")
    claude_version = _get_version(CLAUDE_BIN)
    print(f"  Claude Code: {claude_version}")

    print("Fetching OpenCode version...")
    opencode_version = _get_version(OPENCODE_BIN)
    print(f"  OpenCode: {opencode_version}")

    old_cc, old_oc = _read_versions()
    if claude_version != old_cc:
        print(f"  Claude Code version changed: {old_cc} → {claude_version}")
    if opencode_version != old_oc:
        print(f"  OpenCode version changed: {old_oc} → {opencode_version}")

    print("Fetching Claude models...")
    claude_models = _fetch_claude_models()
    print(f"  Found {len(claude_models)} Claude models")

    print("Fetching OpenCode models...")
    opencode_models = _fetch_opencode_models()
    print(f"  Found {len(opencode_models)} OpenCode models")

    if not claude_models and not opencode_models:
        print("ERROR: could not fetch any models — aborting.", file=sys.stderr)
        sys.exit(1)

    # Preserve existing models if fetch returned nothing for one side
    if not claude_models:
        print("  Warning: keeping existing Claude models (fetch failed)")
        import importlib.util

        spec = importlib.util.spec_from_file_location("reg", REGISTRY_PATH)
        mod = importlib.util.module_from_spec(spec)  # type: ignore[arg-type]
        spec.loader.exec_module(mod)  # type: ignore[union-attr]
        claude_models = mod.CLAUDE_MODELS

    if not opencode_models:
        print("  Warning: keeping existing OpenCode models (fetch failed)")
        import importlib.util

        spec = importlib.util.spec_from_file_location("reg", REGISTRY_PATH)
        mod = importlib.util.module_from_spec(spec)  # type: ignore[arg-type]
        spec.loader.exec_module(mod)  # type: ignore[union-attr]
        opencode_models = mod.OPENCODE_MODELS

    _write_registry(claude_models, opencode_models, claude_version, opencode_version)
    _update_versions_file(claude_version, opencode_version)

    print(f"Written: {REGISTRY_PATH.relative_to(REPO_ROOT)}")
    print(f"Updated: {VERSIONS_PATH.relative_to(REPO_ROOT)}")
    print("Done — commit both files.")


if __name__ == "__main__":
    main()
