# Auto-generated by scripts/fetch_models.py
# Claude Code 2.1.111 / OpenCode 1.14.48
# Regenerate: uv run python scripts/fetch_models.py

from __future__ import annotations

# ---------------------------------------------------------------------------
# Claude Code (Anthropic) — full model IDs accepted by the API + short aliases
# used by the claude runner (e.g. "sonnet" → claude-sonnet-4-6).
# ---------------------------------------------------------------------------
CLAUDE_MODELS: frozenset[str] = frozenset(
    {
        # Claude 4 family
        "claude-opus-4-7",
        "claude-opus-4-7-20250514",
        "claude-sonnet-4-6",
        "claude-sonnet-4-6-20250514",
        "claude-haiku-4-5",
        "claude-haiku-4-5-20251001",
        # Claude 3.7 family
        "claude-3-7-sonnet-20250219",
        "claude-3-7-sonnet-latest",
        # Claude 3.5 family
        "claude-3-5-sonnet-20241022",
        "claude-3-5-sonnet-20240620",
        "claude-3-5-haiku-20241022",
        "claude-3-5-sonnet-latest",
        "claude-3-5-haiku-latest",
        # Claude 3 family
        "claude-3-opus-20240229",
        "claude-3-haiku-20240307",
        "claude-3-sonnet-20240229",
        "claude-3-opus-latest",
        # Short aliases used by the claude_code runner
        "opus",
        "sonnet",
        "haiku",
    }
)

# ---------------------------------------------------------------------------
# OpenCode — provider/model strings accepted by OpenCode's model picker.
# Format: "<provider>/<model-id>" or bare model IDs for default provider.
# ---------------------------------------------------------------------------
OPENCODE_MODELS: frozenset[str] = frozenset(
    {
        # Anthropic (via OpenCode anthropic provider)
        "anthropic/claude-opus-4-7",
        "anthropic/claude-sonnet-4-6",
        "anthropic/claude-haiku-4-5",
        "anthropic/claude-3-7-sonnet-20250219",
        "anthropic/claude-3-5-sonnet-20241022",
        "anthropic/claude-3-5-haiku-20241022",
        "anthropic/claude-3-opus-20240229",
        "anthropic/claude-3-haiku-20240307",
        # OpenAI
        "openai/gpt-4o",
        "openai/gpt-4o-mini",
        "openai/gpt-4-turbo",
        "openai/gpt-4",
        "openai/o1",
        "openai/o1-mini",
        "openai/o3",
        "openai/o3-mini",
        "openai/o4-mini",
        # Google
        "google/gemini-2.5-pro",
        "google/gemini-2.5-flash",
        "google/gemini-2.0-flash",
        "google/gemini-1.5-pro",
        "google/gemini-1.5-flash",
        # Groq
        "groq/llama-3.3-70b-versatile",
        "groq/llama-3.1-8b-instant",
        # Mistral
        "mistral/mistral-large-latest",
        "mistral/mistral-small-latest",
        # Bare aliases (OpenCode default provider)
        "opus",
        "sonnet",
        "haiku",
    }
)
